// client/src/lib/openapi-admin/templates/vue/form.vue
<template>
  <div class="card">
    <div class="card-header">
      <h3 class="card-title">{{ schema.title || 'Create New' }}</h3>
    </div>
    <div class="card-content">
      <form @submit.prevent="onSubmit" class="space-y-4">
        <template v-for="(prop, key) in schema.properties" :key="key">
          <div class="form-field">
            <label :for="key" class="form-label">{{ key }}</label>
            <input
              :id="key"
              v-model="formData[key]"
              :type="prop.type === 'number' ? 'number' : 'text'"
              :required="schema.required?.includes(key)"
              :min="prop.minimum"
              :max="prop.maximum"
              :pattern="prop.pattern"
              class="form-input"
              :placeholder="prop.description || key"
            />
            <span v-if="errors[key]" class="error-text">
              {{ errors[key] }}
            </span>
          </div>
        </template>
        <button 
          type="submit" 
          :disabled="isSubmitting"
          class="submit-button"
        >
          {{ isSubmitting ? 'Submitting...' : 'Submit' }}
        </button>
      </form>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed } from 'vue';
import { useMutation } from '@tanstack/vue-query';

const props = defineProps<{
  schema: any;
  path: string;
  method?: string;
}>();

const formData = ref({});
const errors = ref({});
const isSubmitting = ref(false);

// Initialize form data with empty values
Object.keys(props.schema.properties || {}).forEach(key => {
  formData.value[key] = '';
});

const mutation = useMutation({
  mutationFn: async (data: any) => {
    const res = await fetch(props.path, {
      method: props.method || 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(data),
    });
    if (!res.ok) {
      throw new Error(await res.text());
    }
    return res.json();
  },
  onSuccess: () => {
    // Reset form
    Object.keys(formData.value).forEach(key => {
      formData.value[key] = '';
    });
    errors.value = {};
  },
  onError: (error: Error) => {
    errors.value = { submit: error.message };
  },
});

const onSubmit = async () => {
  errors.value = {};
  isSubmitting.value = true;
  
  try {
    await mutation.mutateAsync(formData.value);
  } finally {
    isSubmitting.value = false;
  }
};
</script>

<style scoped>
.card {
  @apply bg-white rounded-lg shadow-sm;
}
.card-header {
  @apply p-4 border-b;
}
.card-title {
  @apply text-lg font-semibold;
}
.card-content {
  @apply p-4;
}
.form-field {
  @apply space-y-1;
}
.form-label {
  @apply block text-sm font-medium text-gray-700;
}
.form-input {
  @apply w-full px-3 py-2 border rounded-md;
}
.error-text {
  @apply text-sm text-red-500;
}
.submit-button {
  @apply w-full px-4 py-2 text-white bg-blue-600 rounded-md hover:bg-blue-700 disabled:opacity-50;
}
</style>

// client/src/lib/openapi-admin/templates/angular/form.ts
import { Component, Input, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { HttpClient } from '@angular/common/http';

@Component({
  selector: 'app-{{componentName}}',
  template: `
    <div class="card">
      <div class="card-header">
        <h3 class="card-title">{{ schema.title || 'Create New' }}</h3>
      </div>
      <div class="card-content">
        <form [formGroup]="form" (ngSubmit)="onSubmit()" class="space-y-4">
          <ng-container *ngFor="let field of fields">
            <div class="form-field">
              <label [for]="field.key" class="form-label">{{ field.key }}</label>
              <input
                [id]="field.key"
                [type]="field.type"
                [formControlName]="field.key"
                class="form-input"
                [placeholder]="field.description || field.key"
              />
              <span *ngIf="form.get(field.key)?.errors && form.get(field.key)?.touched" class="error-text">
                {{ getErrorMessage(field.key) }}
              </span>
            </div>
          </ng-container>
          
          <button 
            type="submit" 
            [disabled]="isSubmitting || !form.valid"
            class="submit-button"
          >
            {{ isSubmitting ? 'Submitting...' : 'Submit' }}
          </button>
          
          <div *ngIf="error" class="error-message">
            {{ error }}
          </div>
        </form>
      </div>
    </div>
  `,
  styles: [`
    .card {
      @apply bg-white rounded-lg shadow-sm;
    }
    .card-header {
      @apply p-4 border-b;
    }
    .card-title {
      @apply text-lg font-semibold;
    }
    .card-content {
      @apply p-4;
    }
    .form-field {
      @apply space-y-1;
    }
    .form-label {
      @apply block text-sm font-medium text-gray-700;
    }
    .form-input {
      @apply w-full px-3 py-2 border rounded-md;
    }
    .error-text {
      @apply text-sm text-red-500;
    }
    .submit-button {
      @apply w-full px-4 py-2 text-white bg-blue-600 rounded-md hover:bg-blue-700 disabled:opacity-50;
    }
    .error-message {
      @apply mt-4 p-4 bg-red-50 text-red-500 rounded-md;
    }
  `]
})
export class {{componentName}}Component implements OnInit {
  @Input() schema: any;
  @Input() path: string;
  @Input() method = 'POST';

  form: FormGroup;
  isSubmitting = false;
  error: string | null = null;
  fields: Array<{key: string, type: string, description?: string}> = [];

  constructor(
    private fb: FormBuilder,
    private http: HttpClient
  ) {}

  ngOnInit() {
    this.initForm();
  }

  private initForm() {
    const group: any = {};
    this.fields = Object.entries(this.schema.properties || {}).map(([key, prop]: [string, any]) => {
      const validators = [];
      if (this.schema.required?.includes(key)) {
        validators.push(Validators.required);
      }
      if (prop.minimum !== undefined) {
        validators.push(Validators.min(prop.minimum));
      }
      if (prop.maximum !== undefined) {
        validators.push(Validators.max(prop.maximum));
      }
      if (prop.pattern) {
        validators.push(Validators.pattern(prop.pattern));
      }

      group[key] = ['', validators];
      return {
        key,
        type: prop.type === 'number' ? 'number' : 'text',
        description: prop.description
      };
    });

    this.form = this.fb.group(group);
  }

  async onSubmit() {
    if (this.form.valid) {
      this.isSubmitting = true;
      this.error = null;

      try {
        await this.http.request(
          this.method,
          this.path,
          {
            body: this.form.value,
            headers: { 'Content-Type': 'application/json' }
          }
        ).toPromise();
        
        this.form.reset();
      } catch (err: any) {
        this.error = err.message;
      } finally {
        this.isSubmitting = false;
      }
    }
  }

  getErrorMessage(fieldName: string): string {
    const control = this.form.get(fieldName);
    if (!control?.errors) return '';

    if (control.errors['required']) {
      return `${fieldName} is required`;
    }
    if (control.errors['min']) {
      return `${fieldName} must be at least ${control.errors['min'].min}`;
    }
    if (control.errors['max']) {
      return `${fieldName} must be at most ${control.errors['max'].max}`;
    }
    if (control.errors['pattern']) {
      return `${fieldName} has invalid format`;
    }

    return 'Invalid value';
  }
}
